import { ipcMain } from 'electron';
import { getAppVersion, ping } from '../services/HealthService.js';
import { createAccount, deleteAccount, listAccounts, updateAccount, } from '../services/AccountService.js';
import { createCategory, deleteCategory, listCategories, updateCategory, } from '../services/CategoryService.js';
import { createTransaction, deleteTransaction, listTransactions, updateTransaction, } from '../services/TransactionService.js';
import { getDashboardSummary } from '../services/DashboardService.js';
import { exportRecords, openExportFile } from '../services/ExportService.js';
import { backupDatabase, restoreDatabase } from '../services/BackupService.js';
import { checkForAppUpdates, downloadAppUpdate, getUpdaterStatusSnapshot, installDownloadedUpdate, } from '../services/UpdateService.js';
import { createLabourEntry, createLabourer, deleteLabourEntry, deleteLabourer, getLabourSummaries, listLabourEntries, listLabourers, updateLabourEntry, updateLabourer, } from '../services/LabourService.js';
export const registerIpcHandlers = () => {
    ipcMain.handle('app:ping', async () => ping());
    ipcMain.handle('app:version', async () => getAppVersion());
    ipcMain.handle('accounts:list', async () => listAccounts());
    ipcMain.handle('accounts:create', async (_event, payload) => createAccount(payload));
    ipcMain.handle('accounts:update', async (_event, id, payload) => updateAccount(id, payload));
    ipcMain.handle('accounts:delete', async (_event, id) => deleteAccount(id));
    ipcMain.handle('categories:list', async () => listCategories());
    ipcMain.handle('categories:create', async (_event, payload) => createCategory(payload));
    ipcMain.handle('categories:update', async (_event, id, payload) => updateCategory(id, payload));
    ipcMain.handle('categories:delete', async (_event, id) => deleteCategory(id));
    ipcMain.handle('transactions:list', async () => listTransactions());
    ipcMain.handle('transactions:create', async (_event, payload) => createTransaction(payload));
    ipcMain.handle('transactions:update', async (_event, id, payload) => updateTransaction(id, payload));
    ipcMain.handle('transactions:delete', async (_event, id) => deleteTransaction(id));
    ipcMain.handle('labourers:list', async () => listLabourers());
    ipcMain.handle('labourers:create', async (_event, payload) => createLabourer(payload));
    ipcMain.handle('labourers:update', async (_event, id, payload) => updateLabourer(id, payload));
    ipcMain.handle('labourers:delete', async (_event, id) => deleteLabourer(id));
    ipcMain.handle('labour-entries:list', async (_event, labourerId) => listLabourEntries(labourerId));
    ipcMain.handle('labour-entries:create', async (_event, payload) => createLabourEntry(payload));
    ipcMain.handle('labour-entries:update', async (_event, id, payload) => updateLabourEntry(id, payload));
    ipcMain.handle('labour-entries:delete', async (_event, id) => deleteLabourEntry(id));
    ipcMain.handle('labour:summaries', async (_event, labourerId) => getLabourSummaries(labourerId));
    ipcMain.handle('dashboard:summary', async () => getDashboardSummary());
    ipcMain.handle('export:records', async (_event, payload) => exportRecords(payload));
    ipcMain.handle('export:open-file', async (_event, filePath) => openExportFile(filePath));
    ipcMain.handle('backup:create', async () => backupDatabase());
    ipcMain.handle('backup:restore', async () => restoreDatabase());
    ipcMain.handle('updater:status', async () => getUpdaterStatusSnapshot());
    ipcMain.handle('updater:check', async () => checkForAppUpdates());
    ipcMain.handle('updater:download', async () => downloadAppUpdate());
    ipcMain.handle('updater:install', async () => installDownloadedUpdate());
};
